<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconBeranda_button</name>
   <tag></tag>
   <elementGuidId>23e75600-e652-4c5e-af12-8900a799289d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.widget.FrameLayout[@resource-id=&quot;id.binar.fp.secondhand:id/navigation_bar_item_icon_container&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.FrameLayout[@resource-id=&quot;id.binar.fp.secondhand:id/navigation_bar_item_icon_container&quot;])[1]</value>
      <webElementGuid>135fc4de-1928-474b-be12-4b7a49658743</webElementGuid>
   </webElementProperties>
</WebElementEntity>
