<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plus_button</name>
   <tag></tag>
   <elementGuidId>475fad52-6c1a-4eaf-b6db-ea5f1b59b6ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.ImageButton[@content-desc=&quot;Jual&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.ImageButton[@content-desc=&quot;Jual&quot;]</value>
      <webElementGuid>3c314b25-9ead-4754-a4b7-d54e681c541d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
