<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plus_button</name>
   <tag></tag>
   <elementGuidId>dfe2241e-96f8-4d60-9909-bc75bd7741ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.ImageButton[@content-desc=&quot;Jual&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.ImageButton[@content-desc=&quot;Jual&quot;]</value>
      <webElementGuid>a62d08e6-34a2-4c56-93b1-dd7277d2e40f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
