<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_field</name>
   <tag></tag>
   <elementGuidId>9ba48594-d1f3-4a85-af75-5f03cbd49399</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/tl_search&quot;]/android.widget.FrameLayout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/tl_search&quot;]/android.widget.FrameLayout</value>
      <webElementGuid>36b84042-8852-4486-a8cf-4f72bad69b5e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
