<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>semuaKategori_button</name>
   <tag></tag>
   <elementGuidId>cc935515-32bd-460c-a01b-553805e6161c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//androidx.cardview.widget.CardView[@resource-id=&quot;id.binar.fp.secondhand:id/cv_category&quot;])[1]/android.view.ViewGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//androidx.cardview.widget.CardView[@resource-id=&quot;id.binar.fp.secondhand:id/cv_category&quot;])[1]/android.view.ViewGroup</value>
      <webElementGuid>271a4a36-0b23-4cd5-88ea-159d5e635470</webElementGuid>
   </webElementProperties>
</WebElementEntity>
