<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kategori_select</name>
   <tag></tag>
   <elementGuidId>0e2659d4-a3a4-4e13-9498-a85bf361953a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.Spinner[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_category&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.Spinner[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_category&quot;]</value>
      <webElementGuid>015f4fdd-9056-497c-8082-13d761e5e215</webElementGuid>
   </webElementProperties>
</WebElementEntity>
