<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lokasi_field</name>
   <tag></tag>
   <elementGuidId>79243fdc-0f74-4ded-a70c-dc5c158765df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_location&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_location&quot;]</value>
      <webElementGuid>9df6a541-a57e-4c3e-b4fb-ab45f4b2bb8b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
