<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaProduk_field</name>
   <tag></tag>
   <elementGuidId>aa197cbd-07c7-472d-b428-f9a2b982c260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_name&quot;]</value>
      <webElementGuid>6371f4ec-6804-497f-a59c-9943a7462890</webElementGuid>
   </webElementProperties>
</WebElementEntity>
