<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>terbitkan_button</name>
   <tag></tag>
   <elementGuidId>d96949d7-94dd-4ef6-b8ff-1e206a85d11c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.Button[@resource-id=&quot;id.binar.fp.secondhand:id/btn_publish&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.Button[@resource-id=&quot;id.binar.fp.secondhand:id/btn_publish&quot;]</value>
      <webElementGuid>5ffe246c-0b08-425c-a2c0-a5adc38fec25</webElementGuid>
   </webElementProperties>
</WebElementEntity>
