<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleNamaProduk_text</name>
   <tag></tag>
   <elementGuidId>8b1ea0d8-8271-44ce-b14a-eb12294c6d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.TextView[@resource-id=&quot;id.binar.fp.secondhand:id/tv_product_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.TextView[@resource-id=&quot;id.binar.fp.secondhand:id/tv_product_name&quot;]</value>
      <webElementGuid>f2619f28-fe9e-4539-a23e-a698f8b14d1f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
