<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleNamaProduk_text</name>
   <tag></tag>
   <elementGuidId>bcc8cb9b-185a-48b8-9b3f-c8adc9af4f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.TextView[@resource-id=&quot;id.binar.fp.secondhand:id/tv_product_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.TextView[@resource-id=&quot;id.binar.fp.secondhand:id/tv_product_name&quot;]</value>
      <webElementGuid>183bf3e8-edd9-4443-95e7-9118495dead7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
