<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hargaTawar_field</name>
   <tag></tag>
   <elementGuidId>7fa68dc8-de30-45fc-815b-bfc0be5afb3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/etl_product_bid_price&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/etl_product_bid_price&quot;]</value>
      <webElementGuid>8aeb94ed-c4a9-4a98-a4b3-d3696faed8ca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
