<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchBar_field</name>
   <tag></tag>
   <elementGuidId>4a14cda3-7dab-43f1-8309-dab686e04b3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_search&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_search&quot;])[2]</value>
      <webElementGuid>9997b800-f0cc-4180-8fbd-ece5b0ee1a63</webElementGuid>
   </webElementProperties>
</WebElementEntity>
