<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>kotaFieldRegis</name>
   <tag></tag>
   <elementGuidId>3676bfe7-b97a-456b-bfbe-8804ddf614fc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_city&quot;]</value>
      <webElementGuid>1e21227a-328b-4b34-a9bc-df177732b668</webElementGuid>
   </webElementProperties>
   <locator>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_city&quot;]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
