<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>passwordFieldRegis</name>
   <tag></tag>
   <elementGuidId>beaa56c2-7f1b-4e08-8826-00331774e0ea</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_password&quot;])[1]</value>
      <webElementGuid>f8ca95d0-c561-4ab7-8e17-62181a498c08</webElementGuid>
   </webElementProperties>
   <locator>(//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_password&quot;])[1]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
