<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconPhotoCaptureDone_button</name>
   <tag></tag>
   <elementGuidId>33339ef2-b0ef-4f17-bacf-4115c3ed6354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.ImageButton[@content-desc=&quot;Done&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.ImageButton[@content-desc=&quot;Done&quot;]</value>
      <webElementGuid>d486b665-d80e-4def-9738-b7a0bc384772</webElementGuid>
   </webElementProperties>
</WebElementEntity>
