<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>simpan_button</name>
   <tag></tag>
   <elementGuidId>ea1fb519-72ab-40b4-a921-11a015594e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.Button[@resource-id=&quot;id.binar.fp.secondhand:id/btn_save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.Button[@resource-id=&quot;id.binar.fp.secondhand:id/btn_save&quot;]</value>
      <webElementGuid>e6f33009-e6d8-4f77-b210-f50904a2b846</webElementGuid>
   </webElementProperties>
</WebElementEntity>
