<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xButton_field</name>
   <tag></tag>
   <elementGuidId>2ae0771d-f8c8-45b6-8e09-352b034506be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/text_layout&quot;]/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/text_layout&quot;]/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout</value>
      <webElementGuid>7b889700-3049-40fc-b298-c2aceb39db4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
