<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>buttonDaftarRegis</name>
   <tag></tag>
   <elementGuidId>31ccb15c-386d-4ae2-8830-d8efc3037f2c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.Button[@resource-id=&quot;id.binar.fp.secondhand:id/btn_register&quot;]</value>
      <webElementGuid>c952d6de-ce76-4a21-9463-1b016b00d4a0</webElementGuid>
   </webElementProperties>
   <locator>//android.widget.Button[@resource-id=&quot;id.binar.fp.secondhand:id/btn_register&quot;]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
