<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>fieldPassword</name>
   <tag></tag>
   <elementGuidId>a3cd038a-8456-46fb-889c-27a9d6bd10b5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_password&quot;]</value>
      <webElementGuid>0c365078-4819-4c8b-84f7-92ba317874f9</webElementGuid>
   </webElementProperties>
   <locator>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_password&quot;]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
